name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build